version: '3.3'
services:
  web:
    image: node:18.20.2
    restart: always
    working_dir: /home/app
    ports: 
      - "80:3000"
    volumes:
      - ".:/home/app"
    command: "bash -c 'npm install && npm start'"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Gy$qe2z6OchGU'
      MYSQL_DATABASE: user  # Nome do banco de dados a ser criado
      MYSQL_USER: brunoadm          # Nome do usuário a ser criado
      MYSQL_PASSWORD: Ficr@123bc0123  # Senha do usuário a ser criado 
    ports:
      - "3306:3306"  
    volumes:
      - ./db:/var/lib/mysql

